name: Semgrep SAST Scan

on:
  push:
    branches:
      - master

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config=p/ci .